services:
  - type: web
    name: gitanime-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*"
    routes:
      - type: rewrite
        source: /(.*)
        destination: /
